### ISSUE TITLE
Support image uploads as embedded Base64 inside the document

### ISSUE THREAD

**Issue by tiblu** [citizenos/ep_image_upload#1]
**Overview**

Please add support for the uploaded files to be embedded in Base64.

**Cons of external references:**

* Document should be complete, specially when we're talking about signed documents. The data needs to be in one place and not changing. When you refer images from other sources, there is no guarantee them to exist and be unmodified.
* All migrations are a hassle - as the files are referenced from other domains, you need to migrate the images separately and then update the references in the document BUT that modifies the doc.
* All exports are a hassle - to export a document in a different format, you need to download all the referred images and embed them.

**Pros of the external references:**

* Smaller EP database size = quicker backups, less problems with disk space.
* EP scales better as load is distributed, less data read and written.

**TODO:**

- [x] Enable uploaded image to be embedded in Base64
- [x] Make sure embedded Base64 images have same restrictions possible as for other images. (file size and format limits).
- [x] Base64 to be the default configuration.
- [ ] IF possible, downscale oversize images to fit the limits.

**Comment by tiblu** [comment]
Moved out of Winter Push For Perfection (https://github.com/orgs/citizenos/projects/2) as we support local file system uploads and that should satisfy 99% of Users.
