### ISSUE TITLE
Functionality report Firefox and Chrome

### ISSUE THREAD

**Issue by Oremountainflorian** [citizenos/ep_image_upload#11]
**Edited, bold notes by JM**

Motivated by [the issue](https://github.com/JohnMcLear/ep_copy_paste_images/issues/17) and @JohnMcLear answer it wanted to write an report! 

Still left to do:

- [ ] Drag and drop shouldn't create duplicates
- [x] https://github.com/citizenos/ep_image_upload/issues/8

**Details** 

OS: Win 8.1
Browser: Firefox 75.0
Testpad: https://board.net/ (I suppose they have ep_copy_paste_images as well as ep_image_upload installed)

**Drag and Drop inside Pad**

- [ ] Drag and Drop onto a blank line `Works` (image is copied so we have it twice) **- confirmed, will fix today**
- [x] Drag and drop onto content with a line `doesn't work (neither left nor right nor in beetween)` ** - it puts it on the prior line**

**Copy to clipboard/ Paste (using control c / v) inside Pad**

- [x] Paste onto a blank line `doesn't work`
- [x] Paste onto a line populated with content `doesn't work`
- [ ] right click copy/paste `doesn't work` **- confirmed, due to https://github.com/citizenos/ep_image_upload/issues/8**

**Cut to clipboard/ Paste (using control x / v)**

- [x] Paste onto a blank line `doesn't work`
- [x] Paste onto a line populated with content `doesn't work`
- [x] right click cut/paste `doesn't work`

**Image appearance**

- [x] Image is never distorted `correct`
- [x] Image has correct color balance `correct`

**Alignment**

- [x] Image can be aligned using ep_align  `no statement possible`

**Resize**

- [x] Can resize the image `yes, using tab (resize smaller) or shift+tab (resize larger until original size is reached) when the cursor is left of the image` ** I love this hack but I don't think it's suitable as it's not a clear UX, still, I can't fault you 👯 **

**Browser Resize**

- [x]  Can still nagivate the page `yes`
- [x]  Images can be moved / selected / resized 
  - [ ]  select `Image can never be selected by tipping it, but it can be selected by dragging the cursor over several lines. But then ctrl+c/ctrl+x works to move it for example to libre office (so it's in the clipboard), but when it's copied to another place in the pad it disappears)` **- confirmed, due to https://github.com/citizenos/ep_image_upload/issues/8**
  - [x]  resize `works with tab/shift+tab like described above`

**Keyboard**

- [ ]  Caret can be moved between images `yes, but when we have 2 images and the caret is in beetween these two, delete doesn't delete the respective line but rather the image below` **- confirmed, due to https://github.com/citizenos/ep_image_upload/issues/8**
- [ ]  Backspace deletes an image when caret is placed after the image `not possible, because caret/cursor always jumps to the left` **- confirmed, due to https://github.com/citizenos/ep_image_upload/issues/8**
- [x]  Delete removes an image when caret is placed before the image `yes`
- [ ] Backspace doesn't deletes an image when caret is placed before the image - **- confirmed, due to https://github.com/citizenos/ep_image_upload/issues/8**

**Further observations**
- [x]  when I delete an image, it **can** be restored with ctrl+z (doesn't work with ep_copy_paste_images)
- [ ]  being in line below and Backspace doesn't delete the image but rather jumps to the left of the image **- confirmed, due to https://github.com/citizenos/ep_image_upload/issues/8**
- [ ]  when image is in the last line, it isn't possible to create an new line below. Enter moves the image below to the new line. Moving the cursor to right of the image isn't possbile as it moves directly back left **- confirmed, due to https://github.com/citizenos/ep_image_upload/issues/8**
- [ ] when several images are inside the pad, ctrl+z destorys several and then they can't be restored - ** unable to replicate **

**Comment by Oremountainflorian** [comment]
**Details** 

OS: Win 8.1
Browser: Chrome Version 81.0.4044.113
Testpad: https://board.net/ (I suppose they have ep_copy_paste_images as well as ep_image_upload installed)

**Drag and Drop inside Pad**

- Drag and Drop onto a blank line `Doesn't work`
- Drag and drop onto content with a line `works when cursor is left to the text but not when in be`

**Copy to clipboard/ Paste (using control c / v) inside Pad**

- Paste onto a blank line `doesn't work`
- Paste onto a line populated with content `doesn't work`
- right click copy/paste `doesn't work`

**Cut to clipboard/ Paste (using control x / v)**

- Paste onto a blank line `doesn't work`
- Paste onto a line populated with content `doesn't work`
- right click cut/paste `doesn't work`

**Image appearance**

- Image is never distorted `correct`
- Image has correct color balance `correct`

**Alignment**

- Image can be aligned using ep_align  `no statement possible`

**Resize**

- Can resize the image `yes, using tab (resize smaller) or shift+tab (resize larger until original size is reached) when the cursor is left of the image`

**Browser Resize**

- Can still nagivate the page `yes`
- Images can be moved / selected / resized 
  - select `Image can never be selected by tipping it, but it can be selected by dragging the cursor over several lines. But then ctrl+c/ctrl+x works to move it for example to libre office (so it's in the clipboard), but when it's copied to another place in the pad it disappears)`
  - resize `works with tab/shift+tab like described above`

**Keyboard**

- Caret can be moved between images `yes, but when we have 2 images and the caret is in beetween these two, delete doesn't delete the respective line but rather the image below`
- Backspace deletes an image when caret is placed after the image `not possible, because caret/cursor always jumps to the left`
- Delete removes an image when caret is placed before the image `yes`
- Backspace deletes an image when caret is placed before the image `yes`

**Further observations**
- when I delete an image, it can be restored with ctrl+z (but not when cut with ctrl+x)
- being in line below and Backspace doesn't delete the image but rather jumps to the left of the image
- when image is in the last line, it isn't possible to create an new line below. Enter moves the image below to the new line. Moving the cursor to right of the image isn't possbile as it moves directly back left
- when several images are inside the pad, ctrl+z destorys several and then they can't be restored

**Comment by tiblu** [comment]
Thanks for the very detailed report! We'll have a look at this and prioritize.
We have 1.5 developers in the organization so it may not get a very high priority.
We welcome all pull reqests!

**Comment by loorm** [comment]
Triage 23. We will go through the report and create separate Github issues, where we are able to replicate errors. Then these issues will be linked here and will be separately prioritized and solved.

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.

**Comment by JohnMcLear** [comment]
I distilled this down to the issues left to resolve as a good majority are now done:

- [ ] https://github.com/citizenos/ep_image_upload/issues/8
- [ ] Drag and drop shouldn't create duplicates (possibly related to #18 

So TLDR is #8 needs dealing with and this might take a core change which wont be available till 1.8.9 ~March 2021.

**Comment by loorm** [comment]
@tiblu @ilmartyrk Any update on this re the new EP version?

**Comment by ilmartyrk** [comment]
@loorm the cursor positioning issue was closed due to unable to fix it in the EP core. Drag and drop needs some investigation

**Comment by loorm** [comment]
Got it! Assigning for Triage, so you can timebox the investigation.

**Comment by anettlinno** [comment]
Triage 47. Needs code review and testing. Esti. investigation time 4h. Sending to investigation.

**Comment by ilmartyrk** [comment]
@anettlinno had a look, Seems that drag and drop works in firefox. But in Chrome and Opera it opens image in new tab. When trying to drag and drop image from new tab it adds the url of the image as in my local pc starting with C://... thus not starting upload. I guess that to make this feature work there needs to be extra functionality added for it to work in Chrome and Opera too, Also regarding the resize using tab and shift+tab. This acutally adds or removes indentation. But it doesn't have permanent effect in exported document. It also depends on browser window/screen size. So it kind of visually works for  a single user, but for it to really have similar effect on all other users too, it should have changes written into code

**Comment by anettlinno** [comment]
@ilmartyrk thanks for the update! As it is not urgent thing for users then I would propose to park this issue until we decide if we are going to continue with EP editor or change it to any other. 
I´m sending it back to In prep.
